<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5qGI5L6L5bGV56S6');
$cfg_Cs[3]=array(0,1,1,'6K6+6K6h5Zui6Zif');
$cfg_Cs[4]=array(0,1,1,'5pyN5Yqh6IyD5Zu0');
$cfg_Cs[5]=array(0,1,1,'6KOF5L+u55+l6K+G');
$cfg_Cs[6]=array(0,1,1,'5paw6Ze76LWE6K6v');
$cfg_Cs[7]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[8]=array(6,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[9]=array(6,1,1,'6KGM5Lia5paw6Ze7');
$cfg_Cs[10]=array(2,1,1,'5bel6KOF5qGI5L6L');
$cfg_Cs[11]=array(2,1,1,'5a626KOF5qGI5L6L');
$cfg_Cs[12]=array(0,1,1,'5Zu+5paH5Yqo5oCB');
?>