<?php  exit();
/*
Page: /mymanage/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-09-16 10:59:33
*/
?>
<?php  exit();
/*
Page: /mymanage/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-09-16 10:59:33
*/
?>
<?php  exit();
/*
Page: /dede/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2015-06-22 23:13:47
*/
?>
<?php  exit();
/*
Page: /dede/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2015-06-23 13:28:08
*/
?>
<?php  exit();
/*
Page: /dede/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2015-06-23 13:29:41
*/
?>
