<?php
$z[0]=Array("field","",78,106);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",127,156);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n<tr bgcolor=\"#FFFFFF\">\r\n  <td style=\"padding-left:20px;\" height=\"25\"><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></td>\r\n</tr>\r\n",178,395);
$z[2][4]['row']="100";
$z[2][4]['titlelen']="300";
$z[2][4]['orderby']="pubdate";

?>