<?php
$z[0]=Array("field","if(@me=='1')@me='<a href=\"/about/\" class=\"cur\">';else@me='<a href=\"/about/\">';",333,488);
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[0][4]['function']="GetTopid(@me)";
$z[1]=Array("field","if(@me=='2')@me='<a href=\"/case/\" class=\"cur\">';else@me='<a href=\"/case/\">';",542,695);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[1][4]['function']="GetTopid(@me)";
$z[2]=Array("field","if(@me=='3')@me='<a href=\"/designer/\" class=\"cur\">';else@me='<a href=\"/designer/\">';",745,906);
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[2][4]['function']="GetTopid(@me)";
$z[3]=Array("field","if(@me=='4')@me='<a href=\"/services/\" class=\"cur\">';else@me='<a href=\"/services/\">';",960,1121);
$z[3][4]['name']="typeid";
$z[3][4]['runphp']="yes";
$z[3][4]['function']="GetTopid(@me)";
$z[4]=Array("field","if(@me=='5')@me='<a href=\"/knowledge/\" class=\"cur\">';else@me='<a href=\"/knowledge/\">';",1175,1338);
$z[4][4]['name']="typeid";
$z[4][4]['runphp']="yes";
$z[4][4]['function']="GetTopid(@me)";
$z[5]=Array("field","if(@me=='6')@me='<a href=\"/news/\" class=\"cur\">';else@me='<a href=\"/news/\">';",1393,1546);
$z[5][4]['name']="typeid";
$z[5][4]['runphp']="yes";
$z[5][4]['function']="GetTopid(@me)";
$z[6]=Array("field","if(@me=='7')@me='<a href=\"/contact/\" class=\"cur\">';else@me='<a href=\"/contact/\">';",1596,1755);
$z[6][4]['name']="typeid";
$z[6][4]['runphp']="yes";
$z[6][4]['function']="GetTopid(@me)";

?>