<?php
$z[0]=Array("global","",103,129);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("channelartlist","\r\n<tr bgcolor=\"#F5F5F5\">\r\n  <td height=\"30\" style=\"padding-left:10px;\"><a href=\"{dede:field name='typeurl'/}\" target=\"_blank\"><b>{dede:field name='typename'/}</b></a></td>\r\n</tr>\r\n{dede:arclist row='100' titlelen='300' orderby='pubdate'}\r\n<tr bgcolor=\"#FFFFFF\">\r\n  <td style=\"padding-left:20px;\" height=\"25\"><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></td>\r\n</tr>\r\n{/dede:arclist}\r\n",568,1010);
$z[2]=Array("global","",1147,1174);
$z[2][4]['name']="dede_powerby";

?>