<li>
			  <div class="cp" onMouseOver="this.className='cp1'" onMouseOut="this.className='cp'"><a href="[field:arcurl/]" title="[field:fulltitle/]"><img src="[field:litpic/]" alt="[field:fulltitle/]" /></a></div>
			  <div class="cf" onMouseOver="this.className='cf1'" onMouseOut="this.className='cf'"><a href="[field:arcurl/]"  title="[field:fulltitle/]"><span>[field:title/]</span></a></div>
			</li>