<?php
$z[0]=Array("field","",42,100);
$z[0][4]['name']="typename";
$z[0][4]['function']="cn_substr(@me,50)";
$z[1]=Array("field","",138,166);
$z[1][4]['name']="typeurl";
$z[2]=Array("arclist","\r\n		  <li>\r\n		    <div class=\"pp\" onMouseOver=\"this.className='pp1'\" onMouseOut=\"this.className='pp'\"><a href=\"[field:arcurl/]\" title=\"[field:fulltitle function='htmlspecialchars(@me)'/]\"><img src=\"[field:litpic/]\" alt=\"[field:title function='html2text(@me)'/]\"/></a></div>\r\n			<div class=\"pf\" onMouseOver=\"this.className='pf1'\" onMouseOut=\"this.className='pf'\"><a href=\"[field:arcurl/]\" title=\"[field:fulltitle function='htmlspecialchars(@me)'/]\"><span>[field:title/]</span></a></div>\r\n		  </li>\r\n		  ",216,800);
$z[2][4]['type']="image";
$z[2][4]['row']="3";
$z[2][4]['titlelen']="35";
$z[2][4]['orderby']="pubdate";

?>