<?php
$z[0]=Array("global","",26,83);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",169,184);
$z[2]=Array("fulltitle","",193,244);
$z[2][4]['function']="htmlspecialchars(@me)";
$z[3]=Array("title","",249,263);
$z[4]=Array("infos","",305,319);
$z[5]=Array("pubdate","\r\n      \$a=\"\".strftime('%Y-%m-%d',@me).\"\";\r\n      \$b=strftime('%Y-%m-%d',@me);\r\n      \$ntime = time();\r\n      \$day3 = 3600 * 24 * 3;\r\n      if((\$ntime - @me) < \$day3) @me = \$a;\r\n      else @me =\$b;\r\n    ",378,625);
$z[5][4]['runphp']="yes";
$z[6]=Array("arcurl","",662,677);

?>